AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'test/**/*'

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/Documentation:
  Exclude:
    - 'test/**/*'
Style/AlignHash:
  EnforcedColonStyle: table
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/SignalException:
  EnforcedStyle: semantic

inherit_from: .rubocop_todo.yml
